### ISSUE TITLE
Pydantic 2 Support

### ISSUE THREAD

**Issue by anthony-bark** [traveltime-dev/traveltime-python-sdk#103]
Currently, setup.cfg restricts this library to `pydantic>=1.7.4,<2.0`

Is it possible to loosen this requirement and/or add support for Pydantic 2?

**Comment by arnasbr** [comment]
Working on updating pydantic to V2

**Comment by arnasbr** [comment]
https://github.com/traveltime-dev/traveltime-python-sdk/pull/104

**Comment by arnasbr** [comment]
Refactored `traveltimepy` to use `Pydantic V2`. The changes will be live in release `v3.9.0`
