### ISSUE TITLE
No fare data

### ISSUE THREAD

**Issue by williamnorledge** [traveltime-dev/traveltime-python-sdk#108]
When I request fare data for locations within the UK, I'm now getting back error code 13.

I used to be able to get fare data for the UK. This error has started appearing within the last few days.

**Comment by tomastraveltime** [comment]
Hello William, thank you for the report. We are aware of the problem and we're working on a fix. I have sent you an email earlier, I will follow up when we have the fix released.

**Comment by tomastraveltime** [comment]
@williamnorledge the issue has been resolved.

If you have any further questions please let us know over email.

**Comment by williamnorledge** [comment]
Fantastic! Many thanks for the responses.

Best,
William
