### ISSUE TITLE
Migrate from setuptools to pyproject

### ISSUE THREAD

**Issue by danielnaumau** [traveltime-dev/traveltime-python-sdk#124]
https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

**Comment by pawel-wroniszewski** [comment]
Also use "python -m build" instead of "python setup.py sdist bdist_wheel", as calling setup.py directly is deprecated.
The "build" package needs to be installed first.
https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated

**Comment by arnasbr** [comment]
https://github.com/traveltime-dev/traveltime-python-sdk/pull/125
