### ISSUE TITLE
Update protobuf to the latest version

### ISSUE THREAD

**Issue by flobaudry** [traveltime-dev/traveltime-python-sdk#13]
Could you use the latest version of `protobuf` because the `protobuf` version that you use has some security issues (see https://github.com/advisories/GHSA-8gq9-2x98-w8hf)

**Comment by danielnaumau** [comment]
I updated it, you can use traveltimepy==2.0.6.

**Comment by flobaudry** [comment]
The last version of protobuf is `4.21.12`. You have updated to `3.20.3` which still have security issues
