### ISSUE TITLE
Add support for `/time-map/fast `

### ISSUE THREAD

**Issue by MockusTravelTime** [traveltime-dev/traveltime-python-sdk#137]
Link to [Docs](https://docs.traveltime.com/api/reference/isochrones-fast)

**Comment by arnasbr** [comment]
https://github.com/traveltime-dev/traveltime-python-sdk/pull/145

**Comment by arnasbr** [comment]
nevermind, don't need to wait for #136, cause time-map-fast doesn't have kml anyway
