### ISSUE TITLE
Bug: Wrong field name 'full_range' of Departure and Arrival Search

### ISSUE THREAD

**Issue by MxMartin** [traveltime-dev/traveltime-python-sdk#34]
Hi!

It took me a while to find the cause why the Time Filter API was always only returning one result even when using the range option.
I found the problem:

The 'full_range' field ist sent to the API as `full_range`, though the API expects the field to be named `range`, hence ignoring the range settings.

I could imagine that there are good options out there to write tests to automatically compare the pydantic schemas with the Open API schema to avoid  such issues.

Kind regards,
M

**Comment by MxMartin** [comment]
I created a PR with a proposed fix for this: https://github.com/traveltime-dev/traveltime-python-sdk/pull/35

**Comment by danielnaumau** [comment]
Thanks a lot @MxMartin for noticing this bug. This issue wasn't only in Time Filter but in other queries too, so I fixed it in my pr. Try to use version 3.0.4

**Comment by danielnaumau** [comment]
And it's a very good idea to add tests which will compare pydantic schema with our API schema. I think that we'll add it soon
