### ISSUE TITLE
Data or API bug: Train travelling 200km in 6 minutes

### ISSUE THREAD

**Issue by MxMartin** [traveltime-dev/traveltime-python-sdk#67]
I am not sure if this is the right repo to post his report but I couldn't find a suitable one for the API itself.

I ran into the following issue:

The following request:

`
{"locations": [{"id": "HamburgHbf", "coords": {"lat": 53.5527, "lng": 10.006}}, {"id": "ChkPtCharlie", "coords": {"lat": 52.5072, "lng": 13.3904}}], "departure_searches": [{"id": "ChkPtCharlie", "arrival_location_ids": ["HamburgHbf"], "departure_location_id": "ChkPtCharlie", "departure_time": "2023-06-13T03:00:00+02:00", "travel_time": 14400, "transportation": {"type": "public_transport", "pt_change_delay": null, "walking_time": 3600, "max_changes": null}, "properties": ["travel_time", "distance", "route"], "range": null}], "arrival_searches": []}
`

returns a response (see the bottom of the post for complete response json) where part 30 of the route looks as follows:

```
{'arrival_station': 'Fischmarkt2', 'arrives_at': '06:24', 'coords': [{'lat': 51.89891, 'lng': 11.072545}, {'lat': 51.897327, 'lng': 11.062039}, {'lat': 51.896545, 'lng': 11.067089}, {'lat': 51.894184, 'lng': 11.060748}, {'lat': 51.893845, 'lng': 11.056606}, {'lat': 53.547375, 'lng': 9.950815}], 'departs_at': '06:18', 'departure_station': 'Hauptbahnhof1', 'directions': "Take a train (1 / 1 (of Halberstädter Verkehrs-GmbH) line) from 'Hauptbahnhof1' (leaves at 06:18) to 'Fischmarkt2' (arrives at 06:24) (5 stops)", 'distance': 0, 'id': 30, 'line': '1 / 1 (of Halberstädter Verkehrs-GmbH)', 'mode': 'train', 'num_stops': 5, 'travel_time': 1539, 'type': 'public_transport'}
```

which is odd as both from the origin and destination station names and the associated lat/lng values this bus travels 200km from Halberstadt to Hamburg within 6 minutes. Additionally, the travel time does not match the departure and arrival time, as it is about 24 minutes. But event 24 minutes for 200km airline distance seem strange, hence I suspect an error either in the data or in the API calculating the response.

Kind regards,

For your reference, here's the full response I get from the time filter API:

`{"results":[{"search_id":"ChkPtCharlie","locations":[{"id":"HamburgHbf","properties":[{"travel_time":13539,"distance":0,"route":{"departure_time":"2023-06-13T03:00:31+02:00","arrival_time":"2023-06-13T06:45:39+02:00","parts":[{"id":0,"type":"start_end","mode":"walk","directions":"Start your journey 5 meters north","distance":5,"travel_time":3,"coords":[{"lat":52.5072,"lng":13.3904},{"lat":52.50724950000021,"lng":13.390414000000083}],"direction":"north"},{"id":1,"type":"road","mode":"walk","directions":"Walk 93 meters along Friedrichstraße","distance":93,"travel_time":87,"coords":[{"lat":52.50724950000021,"lng":13.390414000000083},{"lat":52.50740520000021,"lng":13.390440200000084},{"lat":52.5076156999999,"lng":13.39040590000002},{"lat":52.507622600000204,"lng":13.390404800000084},{"lat":52.50769629999979,"lng":13.390345999999992},{"lat":52.5077838999999,"lng":13.39032910000002},{"lat":52.50800629999999,"lng":13.390283600000002},{"lat":52.508084599999805,"lng":13.390271299999993}],"road":"Friedrichstraße"},{"id":2,"type":"road","mode":"walk","directions":"Turn left onto Mauerstraße and walk 414 meters","distance":414,"travel_time":348,"coords":[{"lat":52.508084599999805,"lng":13.390271299999993},{"lat":52.50808199999997,"lng":13.39019909999992},{"lat":52.5080811999999,"lng":13.390161200000021},{"lat":52.508096300000226,"lng":13.390127700000015},{"lat":52.508121300000205,"lng":13.390086400000012},{"lat":52.50847829999998,"lng":13.389473799999921},{"lat":52.50854630000001,"lng":13.38943920000005},{"lat":52.50856469999999,"lng":13.389330199999993},{"lat":52.5087163,"lng":13.389063899999993},{"lat":52.5089264999998,"lng":13.388683},{"lat":52.509058699999805,"lng":13.388542499999993},{"lat":52.509311499999804,"lng":13.388280399999992},{"lat":52.50987999999992,"lng":13.387709100000047},{"lat":52.510055600000015,"lng":13.387532700000033},{"lat":52.510093300000015,"lng":13.387496200000033},{"lat":52.51020619999979,"lng":13.387386799999991},{"lat":52.510310400000016,"lng":13.387288300000034},{"lat":52.51035140000002,"lng":13.387249600000034},{"lat":52.51038819999992,"lng":13.387214800000015},{"lat":52.510413099999965,"lng":13.387191300000008},{"lat":52.51078720000008,"lng":13.386837999999981},{"lat":52.51091179999979,"lng":13.386791700000002},{"lat":52.51099899999992,"lng":13.386777300000015},{"lat":52.51103719999979,"lng":13.386772699999991}],"road":"Mauerstraße","turn":"left"},{"id":3,"type":"road","mode":"walk","directions":"Continue onto Glinkastraße for 98 meters","distance":98,"travel_time":71,"coords":[{"lat":52.51103719999979,"lng":13.386772699999991},{"lat":52.51192419999979,"lng":13.38665099999999}],"road":"Glinkastraße","turn":"straight"},{"id":4,"type":"road","mode":"walk","directions":"Turn left onto Mohrenstraße and walk 43 meters","distance":43,"travel_time":42,"coords":[{"lat":52.51192419999979,"lng":13.38665099999999},{"lat":52.51195710000013,"lng":13.386548699999999},{"lat":52.51194290000159,"lng":13.38631729999994},{"lat":52.5119246,"lng":13.386009799999998}],"road":"Mohrenstraße","turn":"left"},{"id":5,"type":"road","mode":"walk","directions":"Turn right onto Mauerstraße and walk 391 meters","distance":391,"travel_time":294,"coords":[{"lat":52.5119246,"lng":13.386009799999998},{"lat":52.511959300000115,"lng":13.385985999999999},{"lat":52.5120724,"lng":13.385910800000001},{"lat":52.5123329,"lng":13.385704200000003},{"lat":52.51273319999979,"lng":13.385465299999991},{"lat":52.5128769,"lng":13.385394399999976},{"lat":52.51358249999979,"lng":13.385080900000002},{"lat":52.51367300000002,"lng":13.385033099999994},{"lat":52.51444949999979,"lng":13.38478509999999},{"lat":52.51474210000029,"lng":13.384693199999997},{"lat":52.514766700000294,"lng":13.384685399999997},{"lat":52.51506240000003,"lng":13.384591700000005},{"lat":52.5153491999998,"lng":13.384499299999991}],"road":"Mauerstraße","turn":"right"},{"id":6,"type":"road","mode":"walk","directions":"Turn left onto Behrenstraße (B 5) and walk 202 meters","distance":202,"travel_time":176,"coords":[{"lat":52.5153491999998,"lng":13.384499299999991},{"lat":52.51533710000026,"lng":13.384326699999933},{"lat":52.51533300000026,"lng":13.384259000000021},{"lat":52.51527600000026,"lng":13.38330800000002},{"lat":52.51527120000024,"lng":13.383238300000091},{"lat":52.51526390000024,"lng":13.383130500000089},{"lat":52.51520720000003,"lng":13.382301600000005},{"lat":52.51519460000041,"lng":13.382116699999953},{"lat":52.515168699999734,"lng":13.381726199999967},{"lat":52.51516770000075,"lng":13.381711000000047},{"lat":52.51516509999996,"lng":13.381672000000032},{"lat":52.5151407999998,"lng":13.38148769999999}],"road":"Behrenstraße (B 5)","turn":"left"},{"id":7,"type":"road","mode":"walk","directions":"Turn right onto Wilhelmstraße and walk 138 meters","distance":138,"travel_time":140,"coords":[{"lat":52.5151407999998,"lng":13.38148769999999},{"lat":52.51523649999991,"lng":13.381436299999987},{"lat":52.51525249999992,"lng":13.381427699999985},{"lat":52.51526560000074,"lng":13.381420600000045},{"lat":52.515293499999736,"lng":13.381405799999968},{"lat":52.516093800000036,"lng":13.380981500000033},{"lat":52.51621009999991,"lng":13.380919899999986},{"lat":52.5162306000001,"lng":13.380910599999991},{"lat":52.51627140000077,"lng":13.380892200000005},{"lat":52.516345499999794,"lng":13.380858499999992}],"road":"Wilhelmstraße","turn":"right"},{"id":8,"type":"road","mode":"walk","directions":"Turn left onto Unter den Linden and walk 11 meters","distance":11,"travel_time":18,"coords":[{"lat":52.516345499999794,"lng":13.380858499999992},{"lat":52.516336100000686,"lng":13.38069470000006}],"road":"Unter den Linden","turn":"left"},{"id":9,"type":"road","mode":"walk","directions":"Turn right  and walk 349 meters","distance":349,"travel_time":276,"coords":[{"lat":52.516336100000686,"lng":13.38069470000006},{"lat":52.51639970000033,"lng":13.380664500000005},{"lat":52.51644479999998,"lng":13.380643100000038},{"lat":52.51647539999998,"lng":13.380628800000038},{"lat":52.516501599999984,"lng":13.380616300000037},{"lat":52.51653320000122,"lng":13.380601400000021},{"lat":52.51655230000033,"lng":13.380592400000005},{"lat":52.51660790000068,"lng":13.38056610000006},{"lat":52.51665090000031,"lng":13.380545800000009},{"lat":52.516694600000676,"lng":13.380525100000058},{"lat":52.51669769999993,"lng":13.380569600000024},{"lat":52.51672190000012,"lng":13.380564999999967},{"lat":52.51674690000012,"lng":13.380560299999967},{"lat":52.51713830000013,"lng":13.380486400000063},{"lat":52.51737540000013,"lng":13.380441600000063},{"lat":52.51799909999992,"lng":13.380322399999926},{"lat":52.5180319999998,"lng":13.380315800000021},{"lat":52.51806279999985,"lng":13.38030979999999},{"lat":52.5181063999998,"lng":13.380300000000021},{"lat":52.51814199999982,"lng":13.380293700000017},{"lat":52.51828679999992,"lng":13.380266499999925},{"lat":52.51881769999992,"lng":13.380167400000024},{"lat":52.51889729999993,"lng":13.380153700000024},{"lat":52.518968199999925,"lng":13.380152600000024},{"lat":52.519477799999926,"lng":13.380054100000024},{"lat":52.51950239999992,"lng":13.380048700000025}],"turn":"right"},{"id":10,"type":"road","mode":"walk","directions":"Turn left onto Schiffbauerdamm and walk 402 meters","distance":402,"travel_time":289,"coords":[{"lat":52.51950239999992,"lng":13.380048700000025},{"lat":52.51949830000014,"lng":13.380004199999982},{"lat":52.519484800000136,"lng":13.379720699999982},{"lat":52.51947050000026,"lng":13.379496699999994},{"lat":52.51947000000011,"lng":13.379386600000014},{"lat":52.51947149999993,"lng":13.379256599999977},{"lat":52.51947089999993,"lng":13.379154699999978},{"lat":52.5194779000002,"lng":13.379003400000004},{"lat":52.5195036999999,"lng":13.378786700000017},{"lat":52.51959150000011,"lng":13.378323900000016},{"lat":52.5196897999999,"lng":13.377993500000017},{"lat":52.51980570000011,"lng":13.377703800000015},{"lat":52.51993120000018,"lng":13.377426300000014},{"lat":52.52008170000027,"lng":13.377179899999994},{"lat":52.5201105999999,"lng":13.377144200000016},{"lat":52.52027980000011,"lng":13.376947700000015},{"lat":52.52035210000014,"lng":13.37690069999998},{"lat":52.52042900000014,"lng":13.37687599999998},{"lat":52.52045090000003,"lng":13.3768701},{"lat":52.52054470000011,"lng":13.376845100000004},{"lat":52.520707400000106,"lng":13.376807100000004},{"lat":52.52083880000021,"lng":13.376784700000025},{"lat":52.521114599999905,"lng":13.376721900000016},{"lat":52.521320099999876,"lng":13.376660399999963},{"lat":52.52156489999987,"lng":13.376539899999964},{"lat":52.521716200000405,"lng":13.376428299999988}],"road":"Schiffbauerdamm","turn":"left"},{"id":11,"type":"road","mode":"walk","directions":"Slight left  and walk 270 meters","distance":270,"travel_time":195,"coords":[{"lat":52.521716200000405,"lng":13.376428299999988},{"lat":52.52190880000002,"lng":13.37628969999999},{"lat":52.52208340000002,"lng":13.37612339999999},{"lat":52.52215430000041,"lng":13.376042099999989},{"lat":52.522258900000395,"lng":13.375890699999989},{"lat":52.522468800000404,"lng":13.375532299999989},{"lat":52.5227514,"lng":13.374970099999935},{"lat":52.52280420000041,"lng":13.375060999999997},{"lat":52.5228567,"lng":13.374940599999935},{"lat":52.52295450000041,"lng":13.374727599999996},{"lat":52.5231074,"lng":13.374333499999935},{"lat":52.523209000000406,"lng":13.373987799999997},{"lat":52.52324610000006,"lng":13.373832299999977},{"lat":52.52328739999998,"lng":13.373855800000022},{"lat":52.52336819999998,"lng":13.373869500000023}],"turn":"slight_left"},{"id":12,"type":"road","mode":"walk","directions":"Turn left onto Kapelle-Ufer and walk 76 meters","distance":76,"travel_time":55,"coords":[{"lat":52.52336819999998,"lng":13.373869500000023},{"lat":52.523398199999846,"lng":13.373748399999995},{"lat":52.5234393000001,"lng":13.373545000000007},{"lat":52.52350190000027,"lng":13.373124799999996},{"lat":52.52353750000001,"lng":13.37276300000005}],"road":"Kapelle-Ufer","turn":"left"},{"id":13,"type":"road","mode":"walk","directions":"Continue onto Hugo-Preuß-Brücke for 88 meters","distance":88,"travel_time":63,"coords":[{"lat":52.52353750000001,"lng":13.37276300000005},{"lat":52.52355580000022,"lng":13.372424599999936},{"lat":52.52355889999985,"lng":13.372270199999996},{"lat":52.52355820000003,"lng":13.372118299999997},{"lat":52.52355610000003,"lng":13.371995199999997},{"lat":52.52355140000003,"lng":13.371844299999998},{"lat":52.5235404000001,"lng":13.371661600000007},{"lat":52.52352520000001,"lng":13.37146450000005}],"road":"Hugo-Preuß-Brücke","turn":"straight"},{"id":14,"type":"road","mode":"walk","directions":"Continue onto Rahel-Hirsch-Straße for 51 meters","distance":51,"travel_time":37,"coords":[{"lat":52.52352520000001,"lng":13.37146450000005},{"lat":52.523506500000266,"lng":13.371275099999997},{"lat":52.523478300000434,"lng":13.371045300000064},{"lat":52.523452300000436,"lng":13.370880100000065},{"lat":52.52342530000008,"lng":13.370727300000004}],"road":"Rahel-Hirsch-Straße","turn":"straight"},{"id":15,"type":"road","mode":"walk","directions":"Turn right onto Friedrich-List-Ufer and walk 8 meters","distance":8,"travel_time":6,"coords":[{"lat":52.52342530000008,"lng":13.370727300000004},{"lat":52.52347920000044,"lng":13.370709200000064},{"lat":52.523504000000045,"lng":13.37070950000005}],"road":"Friedrich-List-Ufer","turn":"right"},{"id":16,"type":"road","mode":"walk","directions":"Turn left  and walk 15 meters","distance":15,"travel_time":12,"coords":[{"lat":52.523504000000045,"lng":13.37070950000005},{"lat":52.52349380000005,"lng":13.37065710000005},{"lat":52.523455800000406,"lng":13.370481399999997}],"turn":"left"},{"id":17,"type":"road","mode":"walk","directions":"Turn right onto Washingtonplatz and walk 60 meters","distance":60,"travel_time":44,"coords":[{"lat":52.523455800000406,"lng":13.370481399999997},{"lat":52.52349390000005,"lng":13.370511100000012},{"lat":52.523528500000474,"lng":13.370501399999995},{"lat":52.52373539999988,"lng":13.370355599999995},{"lat":52.52396729999989,"lng":13.370192199999995}],"road":"Washingtonplatz","turn":"right"},{"id":18,"type":"road","mode":"walk","directions":"Turn right  and walk 208 meters","distance":208,"travel_time":153,"coords":[{"lat":52.52396729999989,"lng":13.370192199999995},{"lat":52.524002700000196,"lng":13.370329499999999},{"lat":52.5240299000002,"lng":13.370435100000002},{"lat":52.52433039999997,"lng":13.370222400000001},{"lat":52.524604900000476,"lng":13.370028100000061},{"lat":52.5246910000002,"lng":13.369967000000019},{"lat":52.524876100000206,"lng":13.369837000000018},{"lat":52.52505720000013,"lng":13.369709799999953},{"lat":52.52522020000077,"lng":13.36959519999997},{"lat":52.52534010000008,"lng":13.36951089999999},{"lat":52.525548000000825,"lng":13.369369899999974},{"lat":52.525594100000205,"lng":13.369545000000016}],"turn":"right"},{"id":19,"type":"basic","mode":"walk","directions":"","distance":0,"travel_time":0,"coords":[{"lat":52.525594100000205,"lng":13.369545000000016},{"lat":52.525593,"lng":13.369545}]},{"id":20,"type":"public_transport","mode":"train","directions":"Take a train (ICE 10 / Intercity-Express (of DB Fernverkehr AG) line) from 'Berlin Hbf (tief)' (leaves at 03:39) to 'Magdeburg Hbf' (arrives at 04:54) (1 stops)","distance":0,"travel_time":4500,"coords":[{"lat":52.525593,"lng":13.369545},{"lat":52.13035,"lng":11.626891}],"line":"ICE 10 / Intercity-Express (of DB Fernverkehr AG)","departure_station":"Berlin Hbf (tief)","arrival_station":"Magdeburg Hbf","departs_at":"03:39","arrives_at":"04:54","num_stops":1},{"id":21,"type":"basic","mode":"walk","directions":"Leave Magdeburg Hbf","distance":3,"travel_time":6,"coords":[{"lat":52.13035,"lng":11.626891},{"lat":52.13034200000006,"lng":11.626945999999986}]},{"id":22,"type":"road","mode":"walk","directions":"Walk 205 meters","distance":205,"travel_time":152,"coords":[{"lat":52.13034200000006,"lng":11.626945999999986},{"lat":52.130377400000164,"lng":11.626956700000008},{"lat":52.130465100000166,"lng":11.626982900000007},{"lat":52.13049210000016,"lng":11.627006100000012},{"lat":52.13052130000009,"lng":11.626741899999985},{"lat":52.13055030000016,"lng":11.626483700000012},{"lat":52.13058600000016,"lng":11.626164900000012},{"lat":52.13057749999996,"lng":11.626162499999992},{"lat":52.13058099999996,"lng":11.626130999999992},{"lat":52.130611199999954,"lng":11.625857099999992},{"lat":52.130640499999956,"lng":11.625814599999993},{"lat":52.130665300000025,"lng":11.625577800000022},{"lat":52.130669999999945,"lng":11.625533000000036},{"lat":52.130675600000025,"lng":11.625487300000021},{"lat":52.13068779999995,"lng":11.625446000000036},{"lat":52.130753500000004,"lng":11.6254225},{"lat":52.130823599999964,"lng":11.625407599999985},{"lat":52.13083960000016,"lng":11.625404800000007},{"lat":52.130853399999964,"lng":11.625401899999984},{"lat":52.13092040000008,"lng":11.625310699999996},{"lat":52.130918500000064,"lng":11.625276499999998},{"lat":52.130919500000076,"lng":11.625244199999996},{"lat":52.130924900000124,"lng":11.625213},{"lat":52.13093060000013,"lng":11.625182500000001},{"lat":52.130987200000035,"lng":11.625003699999997},{"lat":52.13104820000003,"lng":11.62482590000002},{"lat":52.13106550000013,"lng":11.6246734},{"lat":52.131070699999974,"lng":11.624652899999987},{"lat":52.131082300000045,"lng":11.624607499999998},{"lat":52.13110189999974,"lng":11.624530800000024}]},{"id":23,"type":"road","mode":"walk","directions":"Turn right onto Konrad-Adenauer-Platz and walk 6 meters","distance":6,"travel_time":4,"coords":[{"lat":52.13110189999974,"lng":11.624530800000024},{"lat":52.13115369999975,"lng":11.624566500000022}],"road":"Konrad-Adenauer-Platz","turn":"right"},{"id":24,"type":"road","mode":"walk","directions":"Turn left  and walk 7 meters","distance":7,"travel_time":5,"coords":[{"lat":52.13115369999975,"lng":11.624566500000022},{"lat":52.131184299999966,"lng":11.624476599999989}],"turn":"left"},{"id":25,"type":"basic","mode":"walk","directions":"","distance":6,"travel_time":10,"coords":[{"lat":52.131184299999966,"lng":11.624476599999989},{"lat":52.13117,"lng":11.62438}]},{"id":26,"type":"public_transport","mode":"bus","directions":"Take a bus (RE11 / RE11 (of Abellio Rail Mitteldeutschland GmbH)) from 'Magdeburg Hbf ZOB' (leaves at 05:02) to 'Halberstadt' (arrives at 05:57) (1 stops)","distance":0,"travel_time":3603,"coords":[{"lat":52.13117,"lng":11.62438},{"lat":51.899307,"lng":11.073452}],"line":"RE11 / RE11 (of Abellio Rail Mitteldeutschland GmbH)","departure_station":"Magdeburg Hbf ZOB","arrival_station":"Halberstadt","departs_at":"05:02","arrives_at":"05:57","num_stops":1},{"id":27,"type":"basic","mode":"walk","directions":"Leave Halberstadt","distance":26,"travel_time":38,"coords":[{"lat":51.899307,"lng":11.073452},{"lat":51.8991203,"lng":11.073215000000003}]},{"id":28,"type":"road","mode":"walk","directions":"Walk 55 meters","distance":55,"travel_time":41,"coords":[{"lat":51.8991203,"lng":11.073215000000003},{"lat":51.89904990000002,"lng":11.073173200000003},{"lat":51.89897149999987,"lng":11.07312170000001},{"lat":51.8989678,"lng":11.073061200000042},{"lat":51.89894409999977,"lng":11.072675600000013},{"lat":51.898934699999984,"lng":11.072643500000002},{"lat":51.898912499999774,"lng":11.072569100000013}]},{"id":29,"type":"basic","mode":"walk","directions":"","distance":1,"travel_time":2,"coords":[{"lat":51.898912499999774,"lng":11.072569100000013},{"lat":51.89891,"lng":11.072545}]},{"id":30,"type":"public_transport","mode":"train","directions":"Take a train (1 / 1 (of Halberstädter Verkehrs-GmbH) line) from 'Hauptbahnhof1' (leaves at 06:18) to 'Fischmarkt2' (arrives at 06:24) (5 stops)","distance":0,"travel_time":1539,"coords":[{"lat":51.89891,"lng":11.072545},{"lat":51.897327,"lng":11.062039},{"lat":51.896545,"lng":11.067089},{"lat":51.894184,"lng":11.060748},{"lat":51.893845,"lng":11.056606},{"lat":53.547375,"lng":9.950815}],"line":"1 / 1 (of Halberstädter Verkehrs-GmbH)","departure_station":"Hauptbahnhof1","arrival_station":"Fischmarkt2","departs_at":"06:18","arrives_at":"06:24","num_stops":5},{"id":31,"type":"basic","mode":"walk","directions":"Leave Fischmarkt2","distance":3,"travel_time":5,"coords":[{"lat":53.547375,"lng":9.950815},{"lat":53.54740490000021,"lng":9.950802300000046}]},{"id":32,"type":"road","mode":"walk","directions":"Walk 28 meters along Kirchenstraße","distance":28,"travel_time":21,"coords":[{"lat":53.54740490000021,"lng":9.950802300000046},{"lat":53.547649100000044,"lng":9.950651700000009}],"road":"Kirchenstraße"},{"id":33,"type":"road","mode":"walk","directions":"Turn left onto Amundsenstraße and walk 24 meters","distance":24,"travel_time":18,"coords":[{"lat":53.547649100000044,"lng":9.950651700000009},{"lat":53.54759800000011,"lng":9.95052780000004},{"lat":53.5475066000004,"lng":9.950346199999949}],"road":"Amundsenstraße","turn":"left"},{"id":34,"type":"road","mode":"walk","directions":"Turn right  and walk 85 meters","distance":85,"travel_time":61,"coords":[{"lat":53.5475066000004,"lng":9.950346199999949},{"lat":53.547548999999876,"lng":9.950306299999976},{"lat":53.5476679999999,"lng":9.950208299999968},{"lat":53.54791209999999,"lng":9.950024000000003},{"lat":53.548135400000064,"lng":9.949766900000016},{"lat":53.548162200000014,"lng":9.949684100000006}],"turn":"right"},{"id":35,"type":"road","mode":"walk","directions":"Turn left onto Struenseestraße and walk 330 meters","distance":330,"travel_time":238,"coords":[{"lat":53.548162200000014,"lng":9.949684100000006},{"lat":53.54804780000001,"lng":9.949330800000006},{"lat":53.54783820000011,"lng":9.94858319999997},{"lat":53.547811800000105,"lng":9.948434400000016},{"lat":53.547644300000016,"lng":9.947574300000005},{"lat":53.54748890000002,"lng":9.946431400000005},{"lat":53.547363400000016,"lng":9.945544200000004},{"lat":53.54730289999999,"lng":9.945143700000004},{"lat":53.547283599999844,"lng":9.945004499999973},{"lat":53.54726700000001,"lng":9.944884899999986}],"road":"Struenseestraße","turn":"left"},{"id":36,"type":"road","mode":"walk","directions":"Turn right  and walk 60 meters","distance":60,"travel_time":45,"coords":[{"lat":53.54726700000001,"lng":9.944884899999986},{"lat":53.547315300000015,"lng":9.944869999999986},{"lat":53.547265000000145,"lng":9.94441569999997},{"lat":53.547263700000016,"lng":9.944133400000004},{"lat":53.54732940000002,"lng":9.944085600000005}],"turn":"right"},{"id":37,"type":"basic","mode":"walk","directions":"","distance":42,"travel_time":61,"coords":[{"lat":53.54732940000002,"lng":9.944085600000005},{"lat":53.547715,"lng":9.944036}]},{"id":38,"type":"public_transport","mode":"train","directions":"Take a train (S1 (of S-Bahn Hamburg) line) from 'Hamburg Königstraße' (leaves at 06:33) to 'Hamburg Hbf' (arrives at 06:43) (5 stops)","distance":0,"travel_time":691,"coords":[{"lat":53.547715,"lng":9.944036},{"lat":53.549545,"lng":9.957906},{"lat":53.546199,"lng":9.97085},{"lat":53.549385,"lng":9.984478},{"lat":53.552194,"lng":9.993883},{"lat":53.552433,"lng":10.007807}],"line":"S1 (of S-Bahn Hamburg)","departure_station":"Hamburg Königstraße","arrival_station":"Hamburg Hbf","departs_at":"06:33","arrives_at":"06:43","num_stops":5},{"id":39,"type":"basic","mode":"walk","directions":"Leave Hamburg Hbf","distance":11,"travel_time":17,"coords":[{"lat":53.552433,"lng":10.007807},{"lat":53.5523309000002,"lng":10.007763600000006}]},{"id":40,"type":"road","mode":"walk","directions":"Walk 5 meters","distance":5,"travel_time":4,"coords":[{"lat":53.5523309000002,"lng":10.007763600000006},{"lat":53.552317000000194,"lng":10.007746400000006},{"lat":53.55228170000019,"lng":10.007759300000004}]},{"id":41,"type":"road","mode":"walk","directions":"Turn right onto Südsteg and walk 107 meters","distance":107,"travel_time":78,"coords":[{"lat":53.55228170000019,"lng":10.007759300000004},{"lat":53.55224680000018,"lng":10.007468300000001},{"lat":53.552212500000174,"lng":10.0071814},{"lat":53.552155200000165,"lng":10.006703599999998},{"lat":53.552119200000156,"lng":10.006402799999996},{"lat":53.5520877999997,"lng":10.006140999999971}],"road":"Südsteg","turn":"right"},{"id":42,"type":"road","mode":"walk","directions":"Slight left onto Mö-Passage and walk 1 meters","distance":1,"travel_time":1,"coords":[{"lat":53.5520877999997,"lng":10.006140999999971},{"lat":53.55208020000007,"lng":10.00611940000001}],"road":"Mö-Passage","turn":"slight_left"},{"id":43,"type":"road","mode":"walk","directions":"Turn right  and walk 64 meters","distance":64,"travel_time":47,"coords":[{"lat":53.55208020000007,"lng":10.00611940000001},{"lat":53.552124699999936,"lng":10.006104600000015},{"lat":53.55217610000007,"lng":10.00608849999995},{"lat":53.552207200000076,"lng":10.005948000000044},{"lat":53.55224660000027,"lng":10.005943699999943},{"lat":53.552274500000266,"lng":10.005937999999942},{"lat":53.552604400000085,"lng":10.005791700000023}],"turn":"right"},{"id":44,"type":"start_end","mode":"walk","directions":"Your destination is 17 meters northeast","distance":17,"travel_time":12,"coords":[{"lat":53.552604400000085,"lng":10.005791700000023},{"lat":53.5527,"lng":10.006}],"direction":"northeast"}]}}]}],"unreachable":[]}]}`

**Comment by danielnaumau** [comment]
Thanks for reporting this problem, we found the error and it should be fixed soon

**Comment by danielnaumau** [comment]
as far as I see this bug was fixed yesterday, so I'm closing the issue
