### ISSUE TITLE
Cannot serialize response to json

### ISSUE THREAD

**Issue by EivydasKoc** [traveltime-dev/traveltime-python-sdk#9]
Default json module cannot serialize response objects into json strings. Either add a `.json()` function on response to convert to json string in the SDK or return objects which the default module can serialize.

![image](https://user-images.githubusercontent.com/59711277/207325255-66e73045-dfa7-427c-ac07-e4c5a443964a.png)

**Comment by danielnaumau** [comment]
You just need to run **response.json()**
